export enum SitePaths {
  root = '',
  home = 'home',
  aboutUs = 'about-us',
  careers = 'careers',
  contactUs = 'contact-us',
  electricalServices = 'electrical-services',
  electricalServicesOverview = '',
  commercialElectrician = 'commercial-electrician',
  ranchRuralElectrician = 'ranch-rural-electrician',
  residentialElectrician = 'residential-electrician',
  serviceAreas = 'service-areas',
  banderaTxElectrician = 'bandera-tx-electrician',
  boerneTxElectrician = 'boerne-tx-electrician',
  centerPointTxElectrician = 'center-point-tx-electrician',
  comfortTxElectrician = 'comfort-tx-electrician',
  fredericksburgTxElectrician = 'fredericksburg-tx-electrician',
  helotesTxElectrician = 'helotes-tx-electrician',
  huntTxElectrician = 'hunt-tx-electrician',
  ingramTxElectrician = 'ingram-tx-electrician',
  kerrvilleTxElectrician = 'kerrville-tx-electrician',
  texasHillCountryElectrician = 'texas-hill-country-electrician',
  privacyPolicy = 'privacy-policy',
  termsOfService = 'terms-of-service',
  projects = 'projects',
  testimonials = 'testimonials',
  notFound = '**',
}
